### GENERAL OPTIONS
  # Log file path, by default it saved to /var/log in `tmpfs`/memory, if you want you can change e.g. to:
  # "/persist/aa-proxy-rs.log" and this way it will be saved to SD card (appended, not replaced)
  logfile = "/var/log/aa-proxy-rs.log"

  # Interval of showing data transfer statistics in the log (0 = disabled) [seconds]
  stats_interval = 0

  # Data transfer timeout [seconds], after this idle time the session will be reconnected
  timeout_secs = 10

  # Enable legacy USB mode (some HeadUnits/cars needs this enabled for compatibility)
  legacy = false

  # Enable wired USB connection to phone (VID:PID should be specified, zero is wildcard and can be used for single or both fields)
  # you can obtain it e.g. using `lsusb` after connecting phone,
  # and then use e.g. "18d1:0" which will handle specified phone vendor ID (Google Pixel in this example)
  # wired = "0000:0000"

  # Use a Google Android Auto Desktop Head Unit emulator instead of real HU device (will listen on TCP 5277 port)
  dhu = false

  # UDC Controller name (used in special configurations)
  # udc = "dummy_udc.0"

### DEBUGGING
  # Enable debug info
  debug = false

  # Hex dump level [possible values: disabled, decrypted-input, raw-input, decrypted-output, raw-output, all]
  hexdump_level = "disabled"

  # Disable debug level on console, save it only to logfile (helpful for `hexdump-level` option)
  disable_console_debug = false

### BLUETOOTH AND WIFI RELATED
  # BLE advertising
  advertise = false

  # BLE device name (how your bluetooth device is visible)
  # btalias = "WirelessAADongle"

  # Auto-connect to phone and initiate connection
  # zeros/wildcard: iterate over all previously connected devices,
  # set it to phone BT MAC address for connecting to this specific phone
  connect = "00:00:00:00:00:00"

  # WLAN / Wi-Fi Hotspot interface (for obtaining IP and BSSID)
  iface = "wlan0"

  # hostapd.conf file location (used for obtaining AP SSID and WPA passphrase)
  hostapd_conf = "/var/run/hostapd.conf"

  # BT keep alive mode: BLE adapter doesn't power off after successful connection,
  # so that the phone can remain connected (used in special configurations)
  keepalive = false

### MITM CONFIGURATION
  # Enable MITM mode
  mitm = false

  # Force DPI
  # dpi = 130

  # remove tap restriction
  remove_tap_restriction = false

  # video in motion
  video_in_motion = false

  # Disable media sink
  disable_media_sink = false

  # Disable TTS sink
  disable_tts_sink = false

  # Developer mode
  developer_mode = false
