name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        build-args: |
          GH_BRANCH=${{ github.ref_name }}
        tags: manio/aa-proxy-rs:${{ github.ref_name }}
        allow: security.insecure
        outputs: build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: aa-proxy-rs
        path: ./build
